namespace Stor
{
	public enum StorApiStatusEnum
	{
		STOR_NO_ERROR,
		STOR_UNKNOWN_ERROR,
		STOR_INIT_FAILED,
		STOR_NOT_SUPPORTED,
		STOR_NOT_IMPLEMENTED,
		STOR_API_ERROR,
		STOR_OP_STARTED,
		STOR_TIME_OUT,
		STOR_DRIVE_ERROR,
		STOR_INVALID_PARAM,
		STOR_SMART_ERROR,
		STOR_OUT_OF_MEMORY
	}
}
