namespace Stor
{
	public enum VolumeStatus
	{
		VOLUME_UNKNOWN,
		VOLUME_NORMAL,
		VOLUME_FAILED,
		VOLUME_DEGRADED,
		VOLUME_REBUILDING,
		VOLUME_MIGRATING,
		VOLUME_VERIFYING,
		VOLUME_INITIALIZING
	}
}
